project:
  type: website

website:
  title: "Rodrigo Mariscal"
  site-url: "http://rodmariscal.com/"
  description: "My personal web page and blog"
  page-footer:
    left: "The views in this website are exclusively my own and do not necessary represent the views of my colleagues or the institution in which I work."
    right:
      - icon: twitter
        href: https://twitter.com/RodMariscal
      - icon: linkedin
        href: https://www.linkedin.com/in/rmariscal/
      - icon: github
        href: https://github.com/rmariscal
      - icon: envelope
        href: mailto:rmariscalparedes@gmail.com
  navbar:
    #logo: img/AS_AD2.png
    background: "dark"
    foreground: "success"
    right:
      - href: about.qmd
        text: About
      - href: econ_share.qmd
        text: Code
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

