project:
  type: website

website:
  title: "Rodrigo Mariscal"
  navbar:
    right:
      - about.qmd
      - personal_blog.qmd
      - icon: github
        href: https://github.com/rmariscal
      - icon: twitter
        href: https://twitter.com/RodMariscal
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

